server:
  port: 8081
spring:
  # 配置数据源
  datasource:
    # 数据源名称，任意
    name: mysql
    url: jdbc:mysql://localhost:3306/1906?ullNamePatternMatchesAll=true&serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    # 数据库连接用户
    username: root
    # 数据库连接密码
    password: root
    # 驱动
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    #配置自动建表：update:没有表新建，有表更新操作
    show-sql: true
    hibernate:
      #控制台显示建表语句
      ddl-auto: update